Try to add lazy component to client component
Error when starting the server:

    SyntaxError: Cannot use 'import.meta' outside a module
        at internalCompileFunction (node:internal/vm:73:18)
        at wrapSafe (node:internal/modules/cjs/loader:1176:20)
        at Module._compile (node:internal/modules/cjs/loader:1218:27)
        at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
        at Module.load (node:internal/modules/cjs/loader:1117:32)
        at Module._load (node:internal/modules/cjs/loader:958:12)
        at Module.require (node:internal/modules/cjs/loader:1141:19)
        at require (node:internal/modules/cjs/helpers:110:18)
        at Object.<anonymous> (/home/tfischbach/code/parcel-rsc-examples/examples/server/dist/Todos.a1afc280.
    js:1:65)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)